steps:
  - name: 'docker:stable'
    entrypoint: sh
    id: "build"
    args:
      - "-c"
      - |
        set -x
        docker build -t gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID .

  - name: 'docker:stable'
    entrypoint: sh
    id: 'image-push'
    env:
      - 'BRANCH_NAME=$BRANCH_NAME'
    args:
      - "-c"
      - |
        set -x
        if [ $BRANCH_NAME == 'master' ]; then
          docker push gcr.io/$PROJECT_ID/$REPO_NAME:$REVISION_ID gcr.io/$PROJECT_ID/$REPO_NAME:latest
        fi
        

timeout: 3000s